### ISSUE TITLE
Determine how transport CO2 estimator could be used in different programming languages

### ISSUE THREAD

**Issue by brylie** [maasglobal/sustainable-mobility-api#7]
This project currently consists of a Python library. However, Python may not be in use in companies or organizations that would benefit from being able to estimate transport CO2. E.g., many companies are using Java or JavaScript for their production backends.

Initial target languages should be, in decreasing order of priority:

- Python
- JavaScript (Node.js)
- Java
- Go
- Ruby
- C#

# Task
- [x] research possibilities for defining cross-language code from a single codebase
- [x] consider whether a generic data structure or storage format could be used instead of coding the model in a specific programming language
- [x] document efforts and findings in this issue as comments
- [x] create a proposal for cross-language approach, to inform the project roadmap

**Comment by brylie** [comment]
Related to #9, as the API-first design approach could produce auto-generated client/server code.

**Comment by brylie** [comment]
Closing this issue, since we now provide an HTTP API that can be called from other programming languages/environments.
