### ISSUE TITLE
Write initial unit test(s) for estimation function

### ISSUE THREAD

**Issue by brylie** [maasglobal/sustainable-mobility-api#8]
We need to write unit tests to lend confidence that this library is working correctly over time. The initial tests can be reasonably simple. The main goal here is to set up the process for writing unit tests in this project.

## Task
- [x] choose an appropriate method to write unit tests in Python projects (e.g., pytest)
- [ ] write initial test(s) for the estimation function
- [ ] document how to run the tests

**Comment by huksley** [comment]
Just tangentially related to this is, it would be great to understand how we can approach integration testing for deployed docker and serverless API endpoint.

**Comment by brylie** [comment]
@MarkusShepherd recommends we use PyTest for testing. I'll try and find some good tutorials/resources. In general, PyTest seems fairly well documented.

@huksley any thoughts or recommendations?
